<a href="<?php echo site_url($c_url."center")?>">个人信息</a>
<a href="<?php echo site_url($c_url."certificate")?>">资质证书</a>
<a href="<?php echo site_url($c_url."favorites")?>">我的收藏</a>
<a href="<?php echo site_url($c_url."wallet")?>">我的钱包</a>
<div class="clear line">&nbsp;</div>
<a href="<?php echo site_url($c_url."retrieval")?>">我的投标</a>
<a href="<?php echo site_url($c_url."listing")?>">最近排期</a>
<a href="<?php echo site_url($c_url."projects")?>">工种项目</a>
<a href="<?php echo site_url($c_url."cases")?>">案例展示</a>
<div class="clear line">&nbsp;</div>
<a href="<?php echo site_url($c_url."friends")?>">我的好友</a>
<a href="<?php echo site_url($c_url."team")?>">团队管理</a>
<a href="<?php echo site_url($c_url."introduce")?>">介绍工人</a>
<a href="<?php echo site_url($c_url."recruitment")?>">招聘求职</a>
<div class="clear line">&nbsp;</div>
<a href="<?php echo site_url($c_url."ads")?>">投放广告</a>
<a href="<?php echo site_url($c_url."orders_door")?>">订单信息</a>
<a href="<?php echo site_url($c_url."msg")?>">消息管理</a>
<a href="<?php echo site_url("action/logout")?>" class="user_login_out">退出管理</a>