<?php $this->load->view('public/validform'); ?>
<br><form class="validform" method="post"><?php if($is_join==false){?><table width="630" border="0" align="center" cellpadding="0" cellspacing="5"><tr><td colspan="2" valign="bottom" style="font-size:16px;font-weight:bold"><?php echo $this->User_Model->links($RUid);?>
&nbsp;&nbsp;我要参与投标!<?php if($isshow_but){?>
&nbsp;&nbsp;<a href="<?php echo site_url("/retrieval/joins")?>?height=355&width=680&ok=1&id=<?php echo $id?>&type=<?php echo $utype?>" title="参加投标投标" class="thickbox" style="font-weight:lighter; font-size:12px;"><img src="<?php echo $img_url?>ico/change.jpg" align="absmiddle" />切换身份</a><?php }?>
</td></tr><tr><td height="1" colspan="2" valign="bottom" bgcolor="#CCCCCC"><input type="hidden" name="rid" id="rid" value="<?php echo $id?>" /></td></tr>
<tr><td height="2" colspan="2" valign="bottom"></td></tr><tr><td colspan="2" valign="bottom">报价：</td></tr><tr><td colspan="2"><input class="inputxt" nullmsg="报价不能为空！" errormsg="报价至少2个字符,最多6个字符" datatype="s2-6" name="skills" type="text" id="skills" value="" />&nbsp;&nbsp;<span style="color:#999">报价至少2个字符,最多6个字符!</span></td></tr>
<tr><td colspan="2" height="2px;"></td></tr> <tr><td colspan="2">留言：</td></tr><tr><td colspan="2"><textarea class="inputxt" name="note" rows="4" id="note" datatype="*" style="width:99%"></textarea></td></tr>
<tr><td width="90" style="color:#F00;"><span class="cm_btu"><input type="submit" class="buttom" id="retrieval_join" value="参与投标"></span></td><td width="90%" style="color:#F00;">&nbsp;&nbsp;<label style="color:#333;"><input name="show" type="checkbox" id="checkbox" value="1" checked="checked" />&nbsp;是否显示留言信息</label></td></tr></table><?php }else{?>
<table width="630" border="0" align="center" cellpadding="0" cellspacing="5"><tr><td colspan="2" valign="bottom" style="font-size:16px;font-weight:bold"><?php echo $this->User_Model->links($RUid);?>
&nbsp;&nbsp;已经参与投标!</td></tr><tr><td height="1" colspan="2" valign="bottom" bgcolor="#CCCCCC"><input type="hidden" name="rid" id="rid" value="<?php echo $id?>" /><input type="hidden" name="cancel" id="cancel" value="yes" /></td></tr><tr><td height="2" colspan="2" valign="bottom"></td></tr><tr><td colspan="2" valign="bottom">报价：<?php echo $skills?></td></tr><tr><td colspan="2" height="2px;"></td></tr><tr><td colspan="2">留言：<?php echo $note?></td></tr><tr><td width="90" style="color:#F00;"><span class="diy_buttom2"><input type="submit" class="buttom" value="取消参与"></span></td><td style="color:#F00;">&nbsp;&nbsp;</td></tr></table><?php }?>
</form>